// <auto-generated />
using System;
using IDQ.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IDQ.EntityFramework.Migrations
{
    [DbContext(typeof(IDQDbContext))]
    [Migration("20211028151245_Caja-Add-isDebitoBool")]
    partial class CajaAddisDebitoBool
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("IDQ.Domain.Models.abiertoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAgregado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadSacado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoAgregadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductoSacadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.HasIndex("ProductoAgregadoId");

                    b.HasIndex("ProductoSacadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("abiertoProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.cajaConteoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaCierreID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CajaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiferenciaApertura")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("DiferenciaCierre")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("EfectivoApertura")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("EfectivoCierre")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int>("FechaAperturaID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaCierreID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HoraApertura")
                        .HasColumnType("TEXT");

                    b.Property<string>("HoraCierre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MercadoPagoApertura")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("MercadoPagoCierre")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaCierreID")
                        .IsUnique();

                    b.HasIndex("CajaID")
                        .IsUnique();

                    b.HasIndex("FechaAperturaID");

                    b.HasIndex("FechaCierreID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("cajaConteos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.cajaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorForCajaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Efectivo")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MercadoPago")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("Vuelto")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<bool>("isDebito")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeudorForCajaId");

                    b.HasIndex("FechaId");

                    b.ToTable("caja");
                });

            modelBuilder.Entity("IDQ.Domain.Models.consumoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.HasIndex("ProductoId");

                    b.ToTable("consumosProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.conteoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaEntradaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaSalidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaEntradaId")
                        .IsUnique();

                    b.HasIndex("CajaSalidaId")
                        .IsUnique();

                    b.HasIndex("FechaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("conteos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaPagadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FechaSacadoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPagado")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeudorId");

                    b.HasIndex("FechaPagadoId");

                    b.HasIndex("FechaSacadoId");

                    b.HasIndex("VentaId")
                        .IsUnique();

                    b.ToTable("deudas");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudaProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadAdeudada")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadFaltante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeudaId");

                    b.HasIndex("DeudorId");

                    b.HasIndex("ProductoId");

                    b.ToTable("deudaProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalles")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Resto")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("deudores");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudorPagoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("DeudorId");

                    b.HasIndex("FechaId");

                    b.ToTable("deudorPagos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.fechaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fecha")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("fechas");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ingresoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PagadoMP")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PagadoPesos")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId")
                        .IsUnique();

                    b.HasIndex("FechaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ingresos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ingresoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IngresoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngresoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ingresoProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.medidaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Medida")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoSelectorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TipoSelectorId");

                    b.ToTable("medidas");
                });

            modelBuilder.Entity("IDQ.Domain.Models.medidaSelectorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("medidaSelector");
                });

            modelBuilder.Entity("IDQ.Domain.Models.modificadoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("modificadoProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.motivoRetiroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("retiroMotivos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.productoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codigo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descripcion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FechaModificadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MedidaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecioActual")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioIngreso")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockInicial")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaModificadoId");

                    b.HasIndex("MedidaId");

                    b.HasIndex("TagId");

                    b.ToTable("productos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.proveedorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Celular")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalles")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroDeCliente")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("proveedores");
                });

            modelBuilder.Entity("IDQ.Domain.Models.pseudoCajaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AgregadoEfectivo")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("AgregadoMercadoPago")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("CajaEfectivo")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("CajaMercadoPago")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<string>("Detalles")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Efectivo")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MercadoPago")
                        .HasColumnType("decimal(14, 2)");

                    b.HasKey("Id");

                    b.HasIndex("FechaId");

                    b.ToTable("pseudoCajas");
                });

            modelBuilder.Entity("IDQ.Domain.Models.retiroCajaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MotivoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Pendiente")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioAutorizaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioRetiraId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId");

                    b.HasIndex("FechaId");

                    b.HasIndex("MotivoId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("UsuarioAutorizaId");

                    b.HasIndex("UsuarioRetiraId");

                    b.ToTable("retiros");
                });

            modelBuilder.Entity("IDQ.Domain.Models.sacadoProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaPagadoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FechaSacadoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FechaPagadoId");

                    b.HasIndex("FechaSacadoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("sacadoProductos");
                });

            modelBuilder.Entity("IDQ.Domain.Models.tagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Minimo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("IDQ.Domain.Models.usuarioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contraseña")
                        .HasColumnType("TEXT");

                    b.Property<string>("Detalle")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FechaDeEgresoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaDeIngresoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FechaIngreso")
                        .HasColumnType("TEXT");

                    b.Property<string>("FechaSalida")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nivel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Resto")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<string>("Usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FechaDeEgresoId");

                    b.HasIndex("FechaDeIngresoId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ventaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CajaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hora")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CajaId")
                        .IsUnique();

                    b.HasIndex("DeudorId");

                    b.HasIndex("FechaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ventas");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ventaProductoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadDeuda")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CantidadFaltante")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeudorID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FechaPagadoID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioPagado")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("VentaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeudorID");

                    b.HasIndex("FechaPagadoID");

                    b.HasIndex("ProductoId");

                    b.HasIndex("VentaId");

                    b.ToTable("ventaProductos");
                });

            modelBuilder.Entity("cajaModelventaProductoModel", b =>
                {
                    b.Property<int>("CajasPerVentaProductoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaProductosPerCajaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CajasPerVentaProductoId", "VentaProductosPerCajaId");

                    b.HasIndex("VentaProductosPerCajaId");

                    b.ToTable("cajaModelventaProductoModel");
                });

            modelBuilder.Entity("deudorPagoModelventaModel", b =>
                {
                    b.Property<int>("DeudaorPagosPerVentaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VentaPerDeudorPagoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DeudaorPagosPerVentaId", "VentaPerDeudorPagoId");

                    b.HasIndex("VentaPerDeudorPagoId");

                    b.ToTable("deudorPagoModelventaModel");
                });

            modelBuilder.Entity("deudorPagoModelventaProductoModel", b =>
                {
                    b.Property<int>("VentaProductosPerDeudorPagoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("deudorPagosPerVentaProductoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("VentaProductosPerDeudorPagoId", "deudorPagosPerVentaProductoId");

                    b.HasIndex("deudorPagosPerVentaProductoId");

                    b.ToTable("deudorPagoModelventaProductoModel");
                });

            modelBuilder.Entity("IDQ.Domain.Models.abiertoProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("AbiertoProductosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.productoModel", "ProductoAgregado")
                        .WithMany("AbiertoAgregadoPerProducto")
                        .HasForeignKey("ProductoAgregadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.productoModel", "ProductoSacado")
                        .WithMany("AbiertoSacadoPerProducto")
                        .HasForeignKey("ProductoSacadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("AbiertoProductosPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Fecha");

                    b.Navigation("ProductoAgregado");

                    b.Navigation("ProductoSacado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.cajaConteoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", "CajaCierre")
                        .WithOne("CajaConteoCierreForCaja")
                        .HasForeignKey("IDQ.Domain.Models.cajaConteoModel", "CajaCierreID");

                    b.HasOne("IDQ.Domain.Models.cajaModel", "Caja")
                        .WithOne("CajaConteoForCaja")
                        .HasForeignKey("IDQ.Domain.Models.cajaConteoModel", "CajaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaApertura")
                        .WithMany("CajaConteosAperturaPerFecha")
                        .HasForeignKey("FechaAperturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaCierre")
                        .WithMany("CajaConteosCierrePerFecha")
                        .HasForeignKey("FechaCierreID");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("CajaConteosPerUsuario")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("CajaCierre");

                    b.Navigation("FechaApertura");

                    b.Navigation("FechaCierre");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.cajaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.deudorModel", "DeudorForCaja")
                        .WithMany("cajasPerDeudor")
                        .HasForeignKey("DeudorForCajaId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("CajasPerFecha")
                        .HasForeignKey("FechaId");

                    b.Navigation("DeudorForCaja");

                    b.Navigation("Fecha");
                });

            modelBuilder.Entity("IDQ.Domain.Models.consumoProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("ConsumosProductosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("ConsumoProductosPerProducto")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Fecha");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("IDQ.Domain.Models.conteoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.pseudoCajaModel", "CajaEntrada")
                        .WithOne("ConteoEntrada")
                        .HasForeignKey("IDQ.Domain.Models.conteoModel", "CajaEntradaId");

                    b.HasOne("IDQ.Domain.Models.pseudoCajaModel", "CajaSalida")
                        .WithOne("ConteoSalida")
                        .HasForeignKey("IDQ.Domain.Models.conteoModel", "CajaSalidaId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("ConteosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("ConteosPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("CajaEntrada");

                    b.Navigation("CajaSalida");

                    b.Navigation("Fecha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.deudorModel", "Deudor")
                        .WithMany("deudasPerDeudor")
                        .HasForeignKey("DeudorId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaPagado")
                        .WithMany("DeudasPagadoPerFecha")
                        .HasForeignKey("FechaPagadoId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaSacado")
                        .WithMany("DeudasSacadoPerFecha")
                        .HasForeignKey("FechaSacadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.ventaModel", "Venta")
                        .WithOne("DeudaForVenta")
                        .HasForeignKey("IDQ.Domain.Models.deudaModel", "VentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deudor");

                    b.Navigation("FechaPagado");

                    b.Navigation("FechaSacado");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudaProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.deudaModel", "Deuda")
                        .WithMany("deudaProductosPerDeuda")
                        .HasForeignKey("DeudaId");

                    b.HasOne("IDQ.Domain.Models.deudorModel", "Deudor")
                        .WithMany("deudaProductosPerDeudor")
                        .HasForeignKey("DeudorId");

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("DeudaProductoPerProducto")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Deuda");

                    b.Navigation("Deudor");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudorModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("DeudoresPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudorPagoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", "Caja")
                        .WithMany("DeudorPagosPerCaja")
                        .HasForeignKey("CajaId");

                    b.HasOne("IDQ.Domain.Models.deudorModel", "Deudor")
                        .WithMany("DeudorPagosPerDeudor")
                        .HasForeignKey("DeudorId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("DeudorPagosPerFecha")
                        .HasForeignKey("FechaId");

                    b.Navigation("Caja");

                    b.Navigation("Deudor");

                    b.Navigation("Fecha");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ingresoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", "Caja")
                        .WithOne("IngresoForCaja")
                        .HasForeignKey("IDQ.Domain.Models.ingresoModel", "CajaId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("IngresosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.proveedorModel", "Proveedor")
                        .WithMany("IngresosPerProveedor")
                        .HasForeignKey("ProveedorId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("IngresosPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Caja");

                    b.Navigation("Fecha");

                    b.Navigation("Proveedor");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ingresoProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.ingresoModel", "Ingreso")
                        .WithMany("IngresoProductosPerIngreso")
                        .HasForeignKey("IngresoId");

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("IngresoProductosPerProducto")
                        .HasForeignKey("ProductoId");

                    b.Navigation("Ingreso");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("IDQ.Domain.Models.medidaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.medidaSelectorModel", "TipoSelector")
                        .WithMany("medidasPerMedidaSelector")
                        .HasForeignKey("TipoSelectorId");

                    b.Navigation("TipoSelector");
                });

            modelBuilder.Entity("IDQ.Domain.Models.modificadoProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("ModificadosProductosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("ModificadoProductosPerProducto")
                        .HasForeignKey("ProductoId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("ModificadoProductosPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Fecha");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.productoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaModificado")
                        .WithMany("ProductosModificadosPerFecha")
                        .HasForeignKey("FechaModificadoId");

                    b.HasOne("IDQ.Domain.Models.medidaModel", "Medida")
                        .WithMany("ProductosPerMedida")
                        .HasForeignKey("MedidaId");

                    b.HasOne("IDQ.Domain.Models.tagModel", "Tag")
                        .WithMany("ProductosPerTag")
                        .HasForeignKey("TagId");

                    b.Navigation("FechaModificado");

                    b.Navigation("Medida");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("IDQ.Domain.Models.pseudoCajaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("pseudoCajasPerFecha")
                        .HasForeignKey("FechaId");

                    b.Navigation("Fecha");
                });

            modelBuilder.Entity("IDQ.Domain.Models.retiroCajaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", "Caja")
                        .WithMany("RetirosCajaPerCaja")
                        .HasForeignKey("CajaId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("RetirosPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.motivoRetiroModel", "Motivo")
                        .WithMany("Retiros")
                        .HasForeignKey("MotivoId");

                    b.HasOne("IDQ.Domain.Models.proveedorModel", "Proveedor")
                        .WithMany("RetirosCajaPerProveedor")
                        .HasForeignKey("ProveedorId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "UsuarioAutoriza")
                        .WithMany("RetirosAutorizaPerUsuario")
                        .HasForeignKey("UsuarioAutorizaId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "UsuarioRetira")
                        .WithMany("RetirosRetiraPerUsuario")
                        .HasForeignKey("UsuarioRetiraId");

                    b.Navigation("Caja");

                    b.Navigation("Fecha");

                    b.Navigation("Motivo");

                    b.Navigation("Proveedor");

                    b.Navigation("UsuarioAutoriza");

                    b.Navigation("UsuarioRetira");
                });

            modelBuilder.Entity("IDQ.Domain.Models.sacadoProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaPagado")
                        .WithMany("SacadoProductosPagadosPerFecha")
                        .HasForeignKey("FechaPagadoId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaSacado")
                        .WithMany("SacadoProductosSacadosPerFecha")
                        .HasForeignKey("FechaSacadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("SacadoProductosPerProducto")
                        .HasForeignKey("ProductoId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("SacadoProductosPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("FechaPagado");

                    b.Navigation("FechaSacado");

                    b.Navigation("Producto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.usuarioModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaDeEgreso")
                        .WithMany("UsuariosPerFechaEgreso")
                        .HasForeignKey("FechaDeEgresoId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaDeIngreso")
                        .WithMany("UsuariosPerFechaIngreso")
                        .HasForeignKey("FechaDeIngresoId");

                    b.Navigation("FechaDeEgreso");

                    b.Navigation("FechaDeIngreso");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ventaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", "Caja")
                        .WithOne("VentaForCaja")
                        .HasForeignKey("IDQ.Domain.Models.ventaModel", "CajaId");

                    b.HasOne("IDQ.Domain.Models.deudorModel", "Deudor")
                        .WithMany("VentasPerDeudor")
                        .HasForeignKey("DeudorId");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "Fecha")
                        .WithMany("VentasPerFecha")
                        .HasForeignKey("FechaId");

                    b.HasOne("IDQ.Domain.Models.usuarioModel", "Usuario")
                        .WithMany("VentasPerUsuario")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Caja");

                    b.Navigation("Deudor");

                    b.Navigation("Fecha");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ventaProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.deudorModel", "Deudor")
                        .WithMany("VentaProductosPerDeudor")
                        .HasForeignKey("DeudorID");

                    b.HasOne("IDQ.Domain.Models.fechaModel", "FechaPagado")
                        .WithMany("VentaProductosPagadosPerFecha")
                        .HasForeignKey("FechaPagadoID");

                    b.HasOne("IDQ.Domain.Models.productoModel", "Producto")
                        .WithMany("VentaProductosPerProducto")
                        .HasForeignKey("ProductoId");

                    b.HasOne("IDQ.Domain.Models.ventaModel", "Venta")
                        .WithMany("VentaProductosPerVenta")
                        .HasForeignKey("VentaId");

                    b.Navigation("Deudor");

                    b.Navigation("FechaPagado");

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("cajaModelventaProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.cajaModel", null)
                        .WithMany()
                        .HasForeignKey("CajasPerVentaProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.ventaProductoModel", null)
                        .WithMany()
                        .HasForeignKey("VentaProductosPerCajaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("deudorPagoModelventaModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.deudorPagoModel", null)
                        .WithMany()
                        .HasForeignKey("DeudaorPagosPerVentaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.ventaModel", null)
                        .WithMany()
                        .HasForeignKey("VentaPerDeudorPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("deudorPagoModelventaProductoModel", b =>
                {
                    b.HasOne("IDQ.Domain.Models.ventaProductoModel", null)
                        .WithMany()
                        .HasForeignKey("VentaProductosPerDeudorPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IDQ.Domain.Models.deudorPagoModel", null)
                        .WithMany()
                        .HasForeignKey("deudorPagosPerVentaProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IDQ.Domain.Models.cajaModel", b =>
                {
                    b.Navigation("CajaConteoCierreForCaja");

                    b.Navigation("CajaConteoForCaja");

                    b.Navigation("DeudorPagosPerCaja");

                    b.Navigation("IngresoForCaja");

                    b.Navigation("RetirosCajaPerCaja");

                    b.Navigation("VentaForCaja");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudaModel", b =>
                {
                    b.Navigation("deudaProductosPerDeuda");
                });

            modelBuilder.Entity("IDQ.Domain.Models.deudorModel", b =>
                {
                    b.Navigation("cajasPerDeudor");

                    b.Navigation("deudaProductosPerDeudor");

                    b.Navigation("deudasPerDeudor");

                    b.Navigation("DeudorPagosPerDeudor");

                    b.Navigation("VentaProductosPerDeudor");

                    b.Navigation("VentasPerDeudor");
                });

            modelBuilder.Entity("IDQ.Domain.Models.fechaModel", b =>
                {
                    b.Navigation("AbiertoProductosPerFecha");

                    b.Navigation("CajaConteosAperturaPerFecha");

                    b.Navigation("CajaConteosCierrePerFecha");

                    b.Navigation("CajasPerFecha");

                    b.Navigation("ConsumosProductosPerFecha");

                    b.Navigation("ConteosPerFecha");

                    b.Navigation("DeudasPagadoPerFecha");

                    b.Navigation("DeudasSacadoPerFecha");

                    b.Navigation("DeudorPagosPerFecha");

                    b.Navigation("IngresosPerFecha");

                    b.Navigation("ModificadosProductosPerFecha");

                    b.Navigation("ProductosModificadosPerFecha");

                    b.Navigation("pseudoCajasPerFecha");

                    b.Navigation("RetirosPerFecha");

                    b.Navigation("SacadoProductosPagadosPerFecha");

                    b.Navigation("SacadoProductosSacadosPerFecha");

                    b.Navigation("UsuariosPerFechaEgreso");

                    b.Navigation("UsuariosPerFechaIngreso");

                    b.Navigation("VentaProductosPagadosPerFecha");

                    b.Navigation("VentasPerFecha");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ingresoModel", b =>
                {
                    b.Navigation("IngresoProductosPerIngreso");
                });

            modelBuilder.Entity("IDQ.Domain.Models.medidaModel", b =>
                {
                    b.Navigation("ProductosPerMedida");
                });

            modelBuilder.Entity("IDQ.Domain.Models.medidaSelectorModel", b =>
                {
                    b.Navigation("medidasPerMedidaSelector");
                });

            modelBuilder.Entity("IDQ.Domain.Models.motivoRetiroModel", b =>
                {
                    b.Navigation("Retiros");
                });

            modelBuilder.Entity("IDQ.Domain.Models.productoModel", b =>
                {
                    b.Navigation("AbiertoAgregadoPerProducto");

                    b.Navigation("AbiertoSacadoPerProducto");

                    b.Navigation("ConsumoProductosPerProducto");

                    b.Navigation("DeudaProductoPerProducto");

                    b.Navigation("IngresoProductosPerProducto");

                    b.Navigation("ModificadoProductosPerProducto");

                    b.Navigation("SacadoProductosPerProducto");

                    b.Navigation("VentaProductosPerProducto");
                });

            modelBuilder.Entity("IDQ.Domain.Models.proveedorModel", b =>
                {
                    b.Navigation("IngresosPerProveedor");

                    b.Navigation("RetirosCajaPerProveedor");
                });

            modelBuilder.Entity("IDQ.Domain.Models.pseudoCajaModel", b =>
                {
                    b.Navigation("ConteoEntrada");

                    b.Navigation("ConteoSalida");
                });

            modelBuilder.Entity("IDQ.Domain.Models.tagModel", b =>
                {
                    b.Navigation("ProductosPerTag");
                });

            modelBuilder.Entity("IDQ.Domain.Models.usuarioModel", b =>
                {
                    b.Navigation("AbiertoProductosPerUsuario");

                    b.Navigation("CajaConteosPerUsuario");

                    b.Navigation("ConteosPerUsuario");

                    b.Navigation("DeudoresPerUsuario");

                    b.Navigation("IngresosPerUsuario");

                    b.Navigation("ModificadoProductosPerUsuario");

                    b.Navigation("RetirosAutorizaPerUsuario");

                    b.Navigation("RetirosRetiraPerUsuario");

                    b.Navigation("SacadoProductosPerUsuario");

                    b.Navigation("VentasPerUsuario");
                });

            modelBuilder.Entity("IDQ.Domain.Models.ventaModel", b =>
                {
                    b.Navigation("DeudaForVenta");

                    b.Navigation("VentaProductosPerVenta");
                });
#pragma warning restore 612, 618
        }
    }
}
